# Site settings
title: Olivier Lafleur
email: olivier.lafleur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Professeur au Cégep de Lévis-Lauzon et Coach agile chez Elapse.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.olivierlafleur.com" # the base hostname & protocol for your site
twitter_username: olilafleur
github_username:  olafleur

# Build settings
markdown: kramdown
timezone: America/Montreal
