# Site settings
title: Olivier Lafleur
email: olivier.lafleur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Software Developer chez GoDaddy et Professeur au Cégep de Lévis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://olivierlafleur.com" # the base hostname & protocol for your site
github_username:  olafleur
github_godaddy: olafleur-godaddy

# Build settings
markdown: kramdown
timezone: America/Montreal
