# Site settings
title: Olivier Lafleur
email: olivier.lafleur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enseignant au Département d'informatique du Cégep de Lévis-Lauzon.
  Passionné de l'Open Source et du web ouvert.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.olivierlafleur.com" # the base hostname & protocol for your site
twitter_username: olilafleur
github_username:  olafleur

# Build settings
markdown: kramdown
